### ISSUE TITLE
Where are the issues?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/iiif-root-website#5]
Shouldn't all the issues from iiif.io be here, to be pruned down to just the website ones?

**Comment by zimeon** [comment]
I don't know that there is any way to move them (see e.g https://github.com/holman/ama/issues/413). I had assumed we close/recreate as necessary: seems that there are 26 issues to review: https://github.com/iiif/iiif.io/issues?q=is%3Aissue+is%3Aopen+label%3Awebsite

**Comment by srabun** [comment]
We moved all existing relevant issues over on Sept. 28, 2017.
